
# This file is automatically generated, you probably don't want to edit this

doubleOptions <- if (requireNamespace('jmvcore')) R6::R6Class(
    "doubleOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            asser_g1 = NULL,
            quantisup_g1 = NULL,
            qualisup_g1 = NULL,
            asser_g2 = NULL,
            quantisup_g2 = NULL,
            qualisup_g2 = NULL,
            individus = NULL,
            nFactors = 3,
            abs = 1,
            ord = 2,
            proba = 5,
            partial = NULL, ...) {

            super$initialize(
                package='QM',
                name='double',
                requiresData=TRUE,
                ...)

            private$..asser_g1 <- jmvcore::OptionVariables$new(
                "asser_g1",
                asser_g1,
                suggested=list(
                    "nominal",
                    "ordinal"),
                permitted=list(
                    "factor"))
            private$..quantisup_g1 <- jmvcore::OptionVariables$new(
                "quantisup_g1",
                quantisup_g1,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"))
            private$..qualisup_g1 <- jmvcore::OptionVariables$new(
                "qualisup_g1",
                qualisup_g1,
                suggested=list(
                    "nominal",
                    "ordinal"),
                permitted=list(
                    "factor"))
            private$..asser_g2 <- jmvcore::OptionVariables$new(
                "asser_g2",
                asser_g2,
                suggested=list(
                    "nominal",
                    "ordinal"),
                permitted=list(
                    "factor"))
            private$..quantisup_g2 <- jmvcore::OptionVariables$new(
                "quantisup_g2",
                quantisup_g2,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"))
            private$..qualisup_g2 <- jmvcore::OptionVariables$new(
                "qualisup_g2",
                qualisup_g2,
                suggested=list(
                    "nominal",
                    "ordinal"),
                permitted=list(
                    "factor"))
            private$..individus <- jmvcore::OptionVariable$new(
                "individus",
                individus,
                suggested=list(
                    "nominal"),
                permitted=list(
                    "factor"))
            private$..nFactors <- jmvcore::OptionInteger$new(
                "nFactors",
                nFactors,
                default=3)
            private$..abs <- jmvcore::OptionInteger$new(
                "abs",
                abs,
                default=1)
            private$..ord <- jmvcore::OptionInteger$new(
                "ord",
                ord,
                default=2)
            private$..proba <- jmvcore::OptionNumber$new(
                "proba",
                proba,
                default=5)
            private$..partial <- jmvcore::OptionList$new(
                "partial",
                partial,
                options=list(
                    "Biggest",
                    "Smallest"))

            self$.addOption(private$..asser_g1)
            self$.addOption(private$..quantisup_g1)
            self$.addOption(private$..qualisup_g1)
            self$.addOption(private$..asser_g2)
            self$.addOption(private$..quantisup_g2)
            self$.addOption(private$..qualisup_g2)
            self$.addOption(private$..individus)
            self$.addOption(private$..nFactors)
            self$.addOption(private$..abs)
            self$.addOption(private$..ord)
            self$.addOption(private$..proba)
            self$.addOption(private$..partial)
        }),
    active = list(
        asser_g1 = function() private$..asser_g1$value,
        quantisup_g1 = function() private$..quantisup_g1$value,
        qualisup_g1 = function() private$..qualisup_g1$value,
        asser_g2 = function() private$..asser_g2$value,
        quantisup_g2 = function() private$..quantisup_g2$value,
        qualisup_g2 = function() private$..qualisup_g2$value,
        individus = function() private$..individus$value,
        nFactors = function() private$..nFactors$value,
        abs = function() private$..abs$value,
        ord = function() private$..ord$value,
        proba = function() private$..proba$value,
        partial = function() private$..partial$value),
    private = list(
        ..asser_g1 = NA,
        ..quantisup_g1 = NA,
        ..qualisup_g1 = NA,
        ..asser_g2 = NA,
        ..quantisup_g2 = NA,
        ..qualisup_g2 = NA,
        ..individus = NA,
        ..nFactors = NA,
        ..abs = NA,
        ..ord = NA,
        ..proba = NA,
        ..partial = NA)
)

doubleResults <- if (requireNamespace('jmvcore')) R6::R6Class(
    inherit = jmvcore::Group,
    active = list(
        eigengroup = function() private$.items[["eigengroup"]],
        ploteigen = function() private$.items[["ploteigen"]],
        plotgroup = function() private$.items[["plotgroup"]],
        plotindiv = function() private$.items[["plotindiv"]],
        plotvar = function() private$.items[["plotvar"]],
        dimdesc = function() private$.items[["dimdesc"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Analysis of Two Concepts with Multiple Factor Analysis")
            self$add(R6::R6Class(
                inherit = jmvcore::Group,
                active = list(
                    eigen = function() private$.items[["eigen"]]),
                private = list(),
                public=list(
                    initialize=function(options) {
                        super$initialize(
                            options=options,
                            name="eigengroup",
                            title="Eigenvalue Decomposition")
                        self$add(jmvcore::Table$new(
                            options=options,
                            name="eigen",
                            title="Eigenvalue and (cumulative) percentage of variance",
                            columns=list(
                                list(
                                    `name`="component", 
                                    `title`="", 
                                    `type`="text"),
                                list(
                                    `name`="eigenvalue", 
                                    `title`="Eigenvalue", 
                                    `type`="number"),
                                list(
                                    `name`="purcent", 
                                    `title`="% of variance", 
                                    `type`="number"),
                                list(
                                    `name`="purcentcum", 
                                    `title`="Cumulative % of variance", 
                                    `type`="number"))))}))$new(options=options))
            self$add(jmvcore::Image$new(
                options=options,
                name="ploteigen",
                title="Representation of the Eigenvalues",
                width=600,
                height=500,
                renderFun=".ploteigen"))
            self$add(jmvcore::Image$new(
                options=options,
                name="plotgroup",
                title="Representation of the Groups of Statements",
                width=600,
                height=500,
                renderFun=".plotgroup"))
            self$add(jmvcore::Image$new(
                options=options,
                name="plotindiv",
                title="Representation of the Partial Individuals",
                width=600,
                height=500,
                renderFun=".plotindiv"))
            self$add(jmvcore::Image$new(
                options=options,
                name="plotvar",
                title="Representation of the Statements",
                width=600,
                height=500,
                renderFun=".plotvar"))
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="dimdesc",
                title="Automatic Description of the Axes"))}))

doubleBase <- if (requireNamespace('jmvcore')) R6::R6Class(
    "doubleBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = 'QM',
                name = 'double',
                version = c(1,0,0),
                options = options,
                results = doubleResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE)
        }))

#' Two Concepts with MFA
#'
#' 
#' @param data .
#' @param asser_g1 .
#' @param quantisup_g1 .
#' @param qualisup_g1 .
#' @param asser_g2 .
#' @param quantisup_g2 .
#' @param qualisup_g2 .
#' @param individus .
#' @param nFactors .
#' @param abs .
#' @param ord .
#' @param proba .
#' @param partial .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$eigengroup$eigen} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$ploteigen} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$plotgroup} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$plotindiv} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$plotvar} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$dimdesc} \tab \tab \tab \tab \tab a preformatted \cr
#' }
#'
#' @export
double <- function(
    data,
    asser_g1,
    quantisup_g1,
    qualisup_g1,
    asser_g2,
    quantisup_g2,
    qualisup_g2,
    individus,
    nFactors = 3,
    abs = 1,
    ord = 2,
    proba = 5,
    partial) {

    if ( ! requireNamespace('jmvcore'))
        stop('double requires jmvcore to be installed (restart may be required)')

    if ( ! missing(asser_g1)) asser_g1 <- jmvcore::resolveQuo(jmvcore::enquo(asser_g1))
    if ( ! missing(quantisup_g1)) quantisup_g1 <- jmvcore::resolveQuo(jmvcore::enquo(quantisup_g1))
    if ( ! missing(qualisup_g1)) qualisup_g1 <- jmvcore::resolveQuo(jmvcore::enquo(qualisup_g1))
    if ( ! missing(asser_g2)) asser_g2 <- jmvcore::resolveQuo(jmvcore::enquo(asser_g2))
    if ( ! missing(quantisup_g2)) quantisup_g2 <- jmvcore::resolveQuo(jmvcore::enquo(quantisup_g2))
    if ( ! missing(qualisup_g2)) qualisup_g2 <- jmvcore::resolveQuo(jmvcore::enquo(qualisup_g2))
    if ( ! missing(individus)) individus <- jmvcore::resolveQuo(jmvcore::enquo(individus))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(asser_g1), asser_g1, NULL),
            `if`( ! missing(quantisup_g1), quantisup_g1, NULL),
            `if`( ! missing(qualisup_g1), qualisup_g1, NULL),
            `if`( ! missing(asser_g2), asser_g2, NULL),
            `if`( ! missing(quantisup_g2), quantisup_g2, NULL),
            `if`( ! missing(qualisup_g2), qualisup_g2, NULL),
            `if`( ! missing(individus), individus, NULL))

    for (v in asser_g1) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])
    for (v in qualisup_g1) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])
    for (v in asser_g2) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])
    for (v in qualisup_g2) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])
    for (v in individus) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])

    options <- doubleOptions$new(
        asser_g1 = asser_g1,
        quantisup_g1 = quantisup_g1,
        qualisup_g1 = qualisup_g1,
        asser_g2 = asser_g2,
        quantisup_g2 = quantisup_g2,
        qualisup_g2 = qualisup_g2,
        individus = individus,
        nFactors = nFactors,
        abs = abs,
        ord = ord,
        proba = proba,
        partial = partial)

    analysis <- doubleClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}
