
# This file is automatically generated, you probably don't want to edit this

singleOptions <- if (requireNamespace('jmvcore')) R6::R6Class(
    "singleOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            asser = NULL,
            quantisup = NULL,
            qualisup = NULL,
            individus = NULL,
            nFactors = 3,
            abs = 1,
            ord = 2,
            proba = 0.05,
            quantimod = FALSE,
            varmodqualisup = FALSE,
            modality = NULL,
            ventil = 0,
            modclust = "All",
            nbclust = -1, ...) {

            super$initialize(
                package='QM',
                name='single',
                requiresData=TRUE,
                ...)

            private$..asser <- jmvcore::OptionVariables$new(
                "asser",
                asser,
                suggested=list(
                    "nominal",
                    "ordinal"),
                permitted=list(
                    "factor"))
            private$..quantisup <- jmvcore::OptionVariables$new(
                "quantisup",
                quantisup,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"))
            private$..qualisup <- jmvcore::OptionVariables$new(
                "qualisup",
                qualisup,
                suggested=list(
                    "nominal",
                    "ordinal"),
                permitted=list(
                    "factor"))
            private$..individus <- jmvcore::OptionVariable$new(
                "individus",
                individus,
                suggested=list(
                    "nominal"),
                permitted=list(
                    "factor"))
            private$..nFactors <- jmvcore::OptionInteger$new(
                "nFactors",
                nFactors,
                default=3)
            private$..abs <- jmvcore::OptionInteger$new(
                "abs",
                abs,
                default=1)
            private$..ord <- jmvcore::OptionInteger$new(
                "ord",
                ord,
                default=2)
            private$..proba <- jmvcore::OptionNumber$new(
                "proba",
                proba,
                default=0.05)
            private$..quantimod <- jmvcore::OptionBool$new(
                "quantimod",
                quantimod,
                default=FALSE)
            private$..varmodqualisup <- jmvcore::OptionBool$new(
                "varmodqualisup",
                varmodqualisup,
                default=FALSE)
            private$..modality <- jmvcore::OptionString$new(
                "modality",
                modality)
            private$..ventil <- jmvcore::OptionNumber$new(
                "ventil",
                ventil,
                default=0)
            private$..modclust <- jmvcore::OptionString$new(
                "modclust",
                modclust,
                default="All")
            private$..nbclust <- jmvcore::OptionNumber$new(
                "nbclust",
                nbclust,
                default=-1)

            self$.addOption(private$..asser)
            self$.addOption(private$..quantisup)
            self$.addOption(private$..qualisup)
            self$.addOption(private$..individus)
            self$.addOption(private$..nFactors)
            self$.addOption(private$..abs)
            self$.addOption(private$..ord)
            self$.addOption(private$..proba)
            self$.addOption(private$..quantimod)
            self$.addOption(private$..varmodqualisup)
            self$.addOption(private$..modality)
            self$.addOption(private$..ventil)
            self$.addOption(private$..modclust)
            self$.addOption(private$..nbclust)
        }),
    active = list(
        asser = function() private$..asser$value,
        quantisup = function() private$..quantisup$value,
        qualisup = function() private$..qualisup$value,
        individus = function() private$..individus$value,
        nFactors = function() private$..nFactors$value,
        abs = function() private$..abs$value,
        ord = function() private$..ord$value,
        proba = function() private$..proba$value,
        quantimod = function() private$..quantimod$value,
        varmodqualisup = function() private$..varmodqualisup$value,
        modality = function() private$..modality$value,
        ventil = function() private$..ventil$value,
        modclust = function() private$..modclust$value,
        nbclust = function() private$..nbclust$value),
    private = list(
        ..asser = NA,
        ..quantisup = NA,
        ..qualisup = NA,
        ..individus = NA,
        ..nFactors = NA,
        ..abs = NA,
        ..ord = NA,
        ..proba = NA,
        ..quantimod = NA,
        ..varmodqualisup = NA,
        ..modality = NA,
        ..ventil = NA,
        ..modclust = NA,
        ..nbclust = NA)
)

singleResults <- if (requireNamespace('jmvcore')) R6::R6Class(
    inherit = jmvcore::Group,
    active = list(
        eigengroup = function() private$.items[["eigengroup"]],
        ploteigen = function() private$.items[["ploteigen"]],
        distribution = function() private$.items[["distribution"]],
        plotindiv = function() private$.items[["plotindiv"]],
        plotvar = function() private$.items[["plotvar"]],
        plotquantisup = function() private$.items[["plotquantisup"]],
        plotmod = function() private$.items[["plotmod"]],
        dimdesc = function() private$.items[["dimdesc"]],
        clust = function() private$.items[["clust"]],
        plotclust = function() private$.items[["plotclust"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Analysis of One Concept with Multiple Correspondence Analysis")
            self$add(R6::R6Class(
                inherit = jmvcore::Group,
                active = list(
                    eigen = function() private$.items[["eigen"]]),
                private = list(),
                public=list(
                    initialize=function(options) {
                        super$initialize(
                            options=options,
                            name="eigengroup",
                            title="Eigenvalue Decomposition")
                        self$add(jmvcore::Table$new(
                            options=options,
                            name="eigen",
                            title="Eigenvalue and (cumulative) percentage of variance",
                            columns=list(
                                list(
                                    `name`="component", 
                                    `title`="", 
                                    `type`="text"),
                                list(
                                    `name`="eigenvalue", 
                                    `title`="Eigenvalue", 
                                    `type`="number"),
                                list(
                                    `name`="purcent", 
                                    `title`="% of variance", 
                                    `type`="number"),
                                list(
                                    `name`="purcentcum", 
                                    `title`="Cumulative % of variance", 
                                    `type`="number"))))}))$new(options=options))
            self$add(jmvcore::Image$new(
                options=options,
                name="ploteigen",
                title="Eigenvalue Representation",
                width=600,
                height=500,
                renderFun=".ploteigen"))
            self$add(jmvcore::Image$new(
                options=options,
                name="distribution",
                title="Statements Distribution",
                width=700,
                height=500,
                renderFun=".distribution"))
            self$add(jmvcore::Image$new(
                options=options,
                name="plotindiv",
                title="Representation of the Respondents",
                width=700,
                height=600,
                renderFun=".plotindiv"))
            self$add(jmvcore::Image$new(
                options=options,
                name="plotvar",
                title="Representation of the Statements",
                width=700,
                height=600,
                renderFun=".plotvar"))
            self$add(jmvcore::Image$new(
                options=options,
                name="plotquantisup",
                title="Representation of the Supplementary Variables",
                visible="(quantimod)",
                width=700,
                height=600,
                renderFun=".plotquantisup"))
            self$add(jmvcore::Image$new(
                options=options,
                name="plotmod",
                title="Representation of Statements Categories",
                width=700,
                height=600,
                renderFun=".plotmod"))
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="dimdesc",
                title="Automatic Description of the Axes"))
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="clust",
                title="Automatic Description of the Clusters"))
            self$add(jmvcore::Image$new(
                options=options,
                name="plotclust",
                title="Tree from Hierarchical Clustering",
                width=700,
                height=600,
                renderFun=".plotclust"))}))

singleBase <- if (requireNamespace('jmvcore')) R6::R6Class(
    "singleBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = 'QM',
                name = 'single',
                version = c(1,0,0),
                options = options,
                results = singleResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE)
        }))

#' One Concept with MCA
#'
#' 
#' @param data .
#' @param asser .
#' @param quantisup .
#' @param qualisup .
#' @param individus .
#' @param nFactors .
#' @param abs .
#' @param ord .
#' @param proba .
#' @param quantimod .
#' @param varmodqualisup .
#' @param modality .
#' @param ventil .
#' @param modclust .
#' @param nbclust .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$eigengroup$eigen} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$ploteigen} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$distribution} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$plotindiv} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$plotvar} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$plotquantisup} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$plotmod} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$dimdesc} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$clust} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$plotclust} \tab \tab \tab \tab \tab an image \cr
#' }
#'
#' @export
single <- function(
    data,
    asser,
    quantisup,
    qualisup,
    individus,
    nFactors = 3,
    abs = 1,
    ord = 2,
    proba = 0.05,
    quantimod = FALSE,
    varmodqualisup = FALSE,
    modality,
    ventil = 0,
    modclust = "All",
    nbclust = -1) {

    if ( ! requireNamespace('jmvcore'))
        stop('single requires jmvcore to be installed (restart may be required)')

    if ( ! missing(asser)) asser <- jmvcore::resolveQuo(jmvcore::enquo(asser))
    if ( ! missing(quantisup)) quantisup <- jmvcore::resolveQuo(jmvcore::enquo(quantisup))
    if ( ! missing(qualisup)) qualisup <- jmvcore::resolveQuo(jmvcore::enquo(qualisup))
    if ( ! missing(individus)) individus <- jmvcore::resolveQuo(jmvcore::enquo(individus))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(asser), asser, NULL),
            `if`( ! missing(quantisup), quantisup, NULL),
            `if`( ! missing(qualisup), qualisup, NULL),
            `if`( ! missing(individus), individus, NULL))

    for (v in asser) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])
    for (v in qualisup) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])
    for (v in individus) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])

    options <- singleOptions$new(
        asser = asser,
        quantisup = quantisup,
        qualisup = qualisup,
        individus = individus,
        nFactors = nFactors,
        abs = abs,
        ord = ord,
        proba = proba,
        quantimod = quantimod,
        varmodqualisup = varmodqualisup,
        modality = modality,
        ventil = ventil,
        modclust = modclust,
        nbclust = nbclust)

    analysis <- singleClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}
